on:
  push:
    branches:
      - main

name: Build Angular
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v2

      - name: Setup NodeJS ⚙
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install node_modules 📦
        run: npm install

      - name: Build 🔧
        run: npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: dist/personal-website

      - name: Cache node_modules 💾
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
